import { Arcfour, prng_newstate, rng_psize } from "./prng4";

let rng_state: Arcfour;
let rng_pool: number[] = null;
let rng_pptr: number;

var window2 = {
	ASN1: null,
	Base64: null,
	Hex: null,
	crypto: null,
	href: null
};


// Initialize the pool with junk if needed.
if (rng_pool == null) {
	rng_pool = [];
	rng_pptr = 0;
	let t;

	if (window2.crypto && window2.crypto.getRandomValues) {
		// Extract entropy (2048 bits) from RNG if available
		var z = new Uint32Array(256);
		window2.crypto.getRandomValues(z);
		for (t = 0; t < z.length; ++t) {
			rng_pool[rng_pptr++] = z[t] & 255;
		}
	}
	// Use mouse events for entropy, if we do not have enough entropy by the time
	// we need it, entropy will be generated by Math.random.
	var count = 0;

	const onMouseMoveListener = function(ev: Event & { x: number; y: number; }) {
		count = count || 0;
		if (count >= 256 || rng_pptr >= rng_psize) {
			if (window2.removeEventListener) {
				window2.removeEventListener("mousemove", onMouseMoveListener_1, false);
			} else if (window2.detachEvent) {
				window2.detachEvent("onmousemove", onMouseMoveListener_1);
			}
			return;
		}
		try {
			const mouseCoordinates = ev.x + ev.y;
			rng_pool[rng_pptr++] = mouseCoordinates & 255;
			count += 1;
		} catch (e) {
			// Sometimes Firefox will deny permission to access event properties for some reason. Ignore.
		}
	};
	if (window2.addEventListener) {
		window2.addEventListener("mousemove", onMouseMoveListener_1, false);
	} else if (window2.attachEvent) {
		window2.attachEvent("onmousemove", onMouseMoveListener_1);
	}
}

function rng_get_byte() {
	if (rng_state == null) {
		rng_state = prng_newstate();
		// At this point, we may not have collected enough entropy.  If not, fall back to Math.random
		while (rng_pptr < rng_psize) {
			const random = Math.floor(65536 * Math.random());
			rng_pool[rng_pptr++] = random & 255;
		}
		rng_state.init(rng_pool);
		for (rng_pptr = 0; rng_pptr < rng_pool.length; ++rng_pptr) {
			rng_pool[rng_pptr] = 0;
		}
		rng_pptr = 0;
	}
	// TODO: allow reseeding after first request
	return rng_state.next();
}


export class SecureRandom {

	public nextBytes(ba: number[]) {
		for (let i = 0; i < ba.length; ++i) {
			ba[i] = rng_get_byte();
		}
	}
}